### ISSUE TITLE
Build input files not found

### ISSUE THREAD

**Issue by dpentecost** [LASER-Yi/SwiftUI-APOD#1]
Hi  - I would love to try this project, but I am getting this:

error: Build input files cannot be found: '/Users/Shared/System/Volumes/Data/Users/Liang/Local/Projects/Apod-SwiftUI/Apod-SwiftUI/Views/Components/TextEditor.swift', '/Users/Shared/System/Volumes/Data/Users/Liang/Local/Projects/Apod-SwiftUI/Apod-SwiftUI/Models/UserDefaults+Helper.swift' (in target 'Apod-SwiftUI' from project 'Apod-SwiftUI')

The files are listed in the project but the icons are grayed out and the files do not come up in the editor when clicked on.

Any ideas?

**Comment by LASER-Yi** [comment]
Oh sorry about that, the master branch is currently WIP, maybe you can checkout IOS_13 branch to give it a try ;)
